plan

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -9,168 +9,168 @@ env:
   AWS_REGION: eu-central-1
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    services:
-      postgres:
-        image: postgres:12
-        env:
-          POSTGRES_USER: app
-          POSTGRES_PASSWORD: pass
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 5432:5432
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+#  build:
+#    runs-on: ubuntu-latest
+#    services:
+#      postgres:
+#        image: postgres:12
+#        env:
+#          POSTGRES_USER: app
+#          POSTGRES_PASSWORD: pass
+#        options: >-
+#          --health-cmd pg_isready
+#          --health-interval 10s
+#          --health-timeout 5s
+#          --health-retries 5
+#        ports:
+#          - 5432:5432
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v2
+#
+#      - name: Set up Ruby
+#        uses: ruby/setup-ruby@v1
+#        with:
+#          ruby-version: 2.6.6
+#          bundler: Gemfile.lock
+#
+#      - name: Cache dependencies
+#        uses: actions/cache@v1
+#        with:
+#          path: ~/.bundle
+#          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
+#          restore-keys: |
+#            ${{ runner.os }}-gems-
+#
+#      - name: Install dependencies
+#        run: |
+#          bundle config path ~/.bundle
+#          bundle install --jobs 4 --retry 3
+#
+#      - name: Run rubocop
+#        run: bundle exec rubocop --parallel
+#
+#      - name: Create database
+#        env:
+#          RACK_ENV: test
+#          DATABASE_URL: postgres://app:pass@localhost:5432
+#        run: |
+#          bundle exec rake db:create
+#          bundle exec rake db:migrate
+#
+#      - name: Run tests
+#        env:
+#          RACK_ENV: test
+#          DATABASE_URL: postgresql://app:pass@localhost:5432
+#        run: bundle exec rspec
+#
+#      - name: Generate build ID
+#        id: docker_build_id
+#        run: |
+#          branch=${GITHUB_REF##*/}
+#          sha=${GITHUB_SHA::8}
+#          ts=$(date +'%Y-%m-%d')
+#          nm=${{ github.run_number }}
+#          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}-${nm}"
+#
+#      - name: Save docker image to artifact
+#        run: echo "vnovitskyi/assignment-kittens-store:${{ steps.docker_build_id.outputs.BUILD_ID }}" > docker_image.txt
+#
+#      - name: Create docker image output artifact
+#        uses: actions/upload-artifact@v2
+#        with:
+#          path: docker_image.txt
+#          name: docker_image
+#
+#      - name: Build & push Docker image to Dockerhub
+#        uses: mr-smithers-excellent/docker-build-push@v5
+#        with:
+#          image: vnovitskyi/assignment-kittens-store
+#          registry: docker.io
+#          tags: ${{ steps.docker_build_id.outputs.BUILD_ID }}
+#          username: ${{ secrets.DOCKER_USERNAME }}
+#          password: ${{ secrets.DOCKER_PASSWORD }}
+#
+#      - name: Configure AWS client
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          aws-region: ${{ env.AWS_REGION }}
 
-      - name: Set up Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: 2.6.6
-          bundler: Gemfile.lock
-
-      - name: Cache dependencies
-        uses: actions/cache@v1
-        with:
-          path: ~/.bundle
-          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-gems-
-
-      - name: Install dependencies
-        run: |
-          bundle config path ~/.bundle
-          bundle install --jobs 4 --retry 3
-
-      - name: Run rubocop
-        run: bundle exec rubocop --parallel
-
-      - name: Create database
-        env:
-          RACK_ENV: test
-          DATABASE_URL: postgres://app:pass@localhost:5432
-        run: |
-          bundle exec rake db:create
-          bundle exec rake db:migrate
-
-      - name: Run tests
-        env:
-          RACK_ENV: test
-          DATABASE_URL: postgresql://app:pass@localhost:5432
-        run: bundle exec rspec
-
-      - name: Generate build ID
-        id: docker_build_id
-        run: |
-          branch=${GITHUB_REF##*/}
-          sha=${GITHUB_SHA::8}
-          ts=$(date +'%Y-%m-%d')
-          nm=${{ github.run_number }}
-          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}-${nm}"
-
-      - name: Save docker image to artifact
-        run: echo "vnovitskyi/assignment-kittens-store:${{ steps.docker_build_id.outputs.BUILD_ID }}" > docker_image.txt
-
-      - name: Create docker image output artifact
-        uses: actions/upload-artifact@v2
-        with:
-          path: docker_image.txt
-          name: docker_image
-
-      - name: Build & push Docker image to Dockerhub
-        uses: mr-smithers-excellent/docker-build-push@v5
-        with:
-          image: vnovitskyi/assignment-kittens-store
-          registry: docker.io
-          tags: ${{ steps.docker_build_id.outputs.BUILD_ID }}
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Configure AWS client
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
-
-  infrastructure-live-plan:
-    name: "Infrastructure live plan"
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./ops/tf/global/
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          # terraform_version: 0.13.0:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -check
-
-      - name: Terraform Init
-        id: init
-        run: terraform init
-
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
-
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color
-        continue-on-error: true
-
-      - uses: actions/github-script@0.9.0
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-
-            <details><summary>Show Plan</summary>
-
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-
-            </details>
-
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#  infrastructure-live-plan:
+#    name: "Infrastructure live plan"
+#    runs-on: ubuntu-latest
+#    defaults:
+#      run:
+#        working-directory: ./ops/tf/global/
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v2
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          aws-region: ${{ env.AWS_REGION }}
+#
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v1
+#        with:
+#          # terraform_version: 0.13.0:
+#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#
+#      - name: Terraform Format
+#        id: fmt
+#        run: terraform fmt -check
+#
+#      - name: Terraform Init
+#        id: init
+#        run: terraform init
+#
+#      - name: Terraform Validate
+#        id: validate
+#        run: terraform validate -no-color
+#
+#      - name: Terraform Plan
+#        id: plan
+#        if: github.event_name == 'pull_request'
+#        run: terraform plan -no-color
+#        continue-on-error: true
+#
+#      - uses: actions/github-script@0.9.0
+#        if: github.event_name == 'pull_request'
+#        env:
+#          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#        with:
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#          script: |
+#            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#
+#            <details><summary>Show Plan</summary>
+#
+#            \`\`\`\n
+#            ${process.env.PLAN}
+#            \`\`\`
+#
+#            </details>
+#
+#            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#
+#            github.issues.createComment({
+#              issue_number: context.issue.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              body: output
+#            })
+#
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
 
   infrastructure:
     name: "Infrastructure"
@@ -181,7 +181,7 @@ jobs:
     steps:
       - name: View the PR number
         run: |
-          echo "${{ env.PULL_REQUEST_ID }}"
+          echo "${PULL_REQUEST_ID}"
 
       - name: Checkout
         uses: actions/checkout@v2
